# -*- coding: utf-8 -*-
"""Evidencia de Producto - Momento 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uDt0l-3As67rTlE1ZjrmCX2G7YsiuPXF
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""VISITAS DOMICILIARIAS Y PROCESOS"""

info_visitas = pd.read_csv('/content/drive/MyDrive/CSV/BaseDatos.csv', encoding='ISO-8859-1', sep=';')

info_visitas

info_visitas.shape

info_visitas.head(10)

info_visitas.tail(10)

list(info_visitas['Tipo de proceso'].drop_duplicates().tail(10))

list(info_visitas['Ciudad'].drop_duplicates().tail(10))

list(info_visitas['Nombres'].drop_duplicates())

list(info_visitas['Nivel Educativo'].drop_duplicates())

list(info_visitas['Centro de costo'].drop_duplicates().tail(10))

Nivel_educativo = ['Bachiller',
'Primaria',
'Técnologo',
'otro'
]

Nivel_educativo

list(info_visitas['Apellidos'].drop_duplicates())

df = pd.DataFrame({"Nombres":["Ana","Elena", "Omar", "Rafael"]})

df

plt.figure(figsize=(15, 25))
sns.countplot(y='Tipo de visita', hue='Tipo de proceso', data=info_visitas, palette='pastel', edgecolor='black', dodge=True)
plt.title("Tipo de visita y Tipo de Proceso")
plt.xlabel("Tipo de visita")
plt.ylabel("Tipo de proceso")
plt.legend(title='Tipo de Proceso')
plt.show()